// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace EMPRESTIMO.LIVROS.Models
{
    public partial class EmprestimoLivroContext : DbContext
    {
        public EmprestimoLivroContext()
        {
        }

        public EmprestimoLivroContext(DbContextOptions<EmprestimoLivroContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Livro> Livro { get; set; }
        public virtual DbSet<LivroClienteEmprestimo> LivroClienteEmprestimo { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultSchema("BOOKS_MAIN")
                .UseCollation("USING_NLS_COMP");

            modelBuilder.Entity<Cliente>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
            });

            modelBuilder.Entity<Livro>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
            });

            modelBuilder.Entity<LivroClienteEmprestimo>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedOnAdd();

                entity.Property(e => e.Lceentregue).IsFixedLength();
            });

            modelBuilder.HasSequence("CLIENTE_SEQ");

            modelBuilder.HasSequence("CLIENTE_SEQ1");

            modelBuilder.HasSequence("LIVRO_CLIENTE_EMPRESTIMO_SEQ");

            modelBuilder.HasSequence("LIVRO_SEQ");

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}