// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EMPRESTIMO.LIVROS.Models
{
    [Table("LIVRO")]
    public partial class Livro
    {
        [Key]
        [Column("ID", TypeName = "NUMBER(38)")]
        public decimal Id { get; set; }
        [Required]
        [Column("LIVRONOME")]
        [StringLength(50)]
        [Unicode(false)]
        public string Livronome { get; set; }
        [Required]
        [Column("LIVROAUTOR")]
        [StringLength(200)]
        [Unicode(false)]
        public string Livroautor { get; set; }
        [Required]
        [Column("LIVROEDITORA")]
        [StringLength(100)]
        [Unicode(false)]
        public string Livroeditora { get; set; }
        [Column("LIVROANOPUBLICACAO", TypeName = "DATE")]
        public DateTime Livroanopublicacao { get; set; }
        [Required]
        [Column("LIVROEDICAO")]
        [StringLength(50)]
        [Unicode(false)]
        public string Livroedicao { get; set; }
    }
}